package helpers;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InterBankProto.proto

public final class InterBankProto {
  private InterBankProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InterBankOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InterBank)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 senderAccNo = 1;</code>
     * @return The senderAccNo.
     */
    long getSenderAccNo();

    /**
     * <code>int64 receiverAccNo = 2;</code>
     * @return The receiverAccNo.
     */
    long getReceiverAccNo();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string ifsc = 5;</code>
     * @return The ifsc.
     */
    java.lang.String getIfsc();
    /**
     * <code>string ifsc = 5;</code>
     * @return The bytes for ifsc.
     */
    com.google.protobuf.ByteString
        getIfscBytes();
  }
  /**
   * Protobuf type {@code InterBank}
   */
  public static final class InterBank extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InterBank)
      InterBankOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InterBank.newBuilder() to construct.
    private InterBank(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InterBank() {
      description_ = "";
      ifsc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InterBank();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InterBank(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              senderAccNo_ = input.readInt64();
              break;
            }
            case 16: {

              receiverAccNo_ = input.readInt64();
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              ifsc_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InterBankProto.internal_static_InterBank_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InterBankProto.internal_static_InterBank_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InterBankProto.InterBank.class, InterBankProto.InterBank.Builder.class);
    }

    public static final int SENDERACCNO_FIELD_NUMBER = 1;
    private long senderAccNo_;
    /**
     * <code>int64 senderAccNo = 1;</code>
     * @return The senderAccNo.
     */
    @java.lang.Override
    public long getSenderAccNo() {
      return senderAccNo_;
    }

    public static final int RECEIVERACCNO_FIELD_NUMBER = 2;
    private long receiverAccNo_;
    /**
     * <code>int64 receiverAccNo = 2;</code>
     * @return The receiverAccNo.
     */
    @java.lang.Override
    public long getReceiverAccNo() {
      return receiverAccNo_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IFSC_FIELD_NUMBER = 5;
    private volatile java.lang.Object ifsc_;
    /**
     * <code>string ifsc = 5;</code>
     * @return The ifsc.
     */
    @java.lang.Override
    public java.lang.String getIfsc() {
      java.lang.Object ref = ifsc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ifsc_ = s;
        return s;
      }
    }
    /**
     * <code>string ifsc = 5;</code>
     * @return The bytes for ifsc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIfscBytes() {
      java.lang.Object ref = ifsc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ifsc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (senderAccNo_ != 0L) {
        output.writeInt64(1, senderAccNo_);
      }
      if (receiverAccNo_ != 0L) {
        output.writeInt64(2, receiverAccNo_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      if (!getIfscBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ifsc_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (senderAccNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, senderAccNo_);
      }
      if (receiverAccNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, receiverAccNo_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      if (!getIfscBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ifsc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InterBankProto.InterBank)) {
        return super.equals(obj);
      }
      InterBankProto.InterBank other = (InterBankProto.InterBank) obj;

      if (getSenderAccNo()
          != other.getSenderAccNo()) return false;
      if (getReceiverAccNo()
          != other.getReceiverAccNo()) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getIfsc()
          .equals(other.getIfsc())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERACCNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSenderAccNo());
      hash = (37 * hash) + RECEIVERACCNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiverAccNo());
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + IFSC_FIELD_NUMBER;
      hash = (53 * hash) + getIfsc().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InterBankProto.InterBank parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InterBankProto.InterBank parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InterBankProto.InterBank parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InterBankProto.InterBank parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InterBankProto.InterBank parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InterBankProto.InterBank parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InterBankProto.InterBank parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InterBankProto.InterBank parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InterBankProto.InterBank parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InterBankProto.InterBank parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InterBankProto.InterBank parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InterBankProto.InterBank parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InterBankProto.InterBank prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InterBank}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InterBank)
        InterBankProto.InterBankOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InterBankProto.internal_static_InterBank_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InterBankProto.internal_static_InterBank_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InterBankProto.InterBank.class, InterBankProto.InterBank.Builder.class);
      }

      // Construct using InterBankProto.InterBank.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderAccNo_ = 0L;

        receiverAccNo_ = 0L;

        amount_ = 0D;

        description_ = "";

        ifsc_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InterBankProto.internal_static_InterBank_descriptor;
      }

      @java.lang.Override
      public InterBankProto.InterBank getDefaultInstanceForType() {
        return InterBankProto.InterBank.getDefaultInstance();
      }

      @java.lang.Override
      public InterBankProto.InterBank build() {
        InterBankProto.InterBank result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public InterBankProto.InterBank buildPartial() {
        InterBankProto.InterBank result = new InterBankProto.InterBank(this);
        result.senderAccNo_ = senderAccNo_;
        result.receiverAccNo_ = receiverAccNo_;
        result.amount_ = amount_;
        result.description_ = description_;
        result.ifsc_ = ifsc_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InterBankProto.InterBank) {
          return mergeFrom((InterBankProto.InterBank)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InterBankProto.InterBank other) {
        if (other == InterBankProto.InterBank.getDefaultInstance()) return this;
        if (other.getSenderAccNo() != 0L) {
          setSenderAccNo(other.getSenderAccNo());
        }
        if (other.getReceiverAccNo() != 0L) {
          setReceiverAccNo(other.getReceiverAccNo());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getIfsc().isEmpty()) {
          ifsc_ = other.ifsc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InterBankProto.InterBank parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InterBankProto.InterBank) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long senderAccNo_ ;
      /**
       * <code>int64 senderAccNo = 1;</code>
       * @return The senderAccNo.
       */
      @java.lang.Override
      public long getSenderAccNo() {
        return senderAccNo_;
      }
      /**
       * <code>int64 senderAccNo = 1;</code>
       * @param value The senderAccNo to set.
       * @return This builder for chaining.
       */
      public Builder setSenderAccNo(long value) {
        
        senderAccNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 senderAccNo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderAccNo() {
        
        senderAccNo_ = 0L;
        onChanged();
        return this;
      }

      private long receiverAccNo_ ;
      /**
       * <code>int64 receiverAccNo = 2;</code>
       * @return The receiverAccNo.
       */
      @java.lang.Override
      public long getReceiverAccNo() {
        return receiverAccNo_;
      }
      /**
       * <code>int64 receiverAccNo = 2;</code>
       * @param value The receiverAccNo to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverAccNo(long value) {
        
        receiverAccNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiverAccNo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverAccNo() {
        
        receiverAccNo_ = 0L;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 4;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 4;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ifsc_ = "";
      /**
       * <code>string ifsc = 5;</code>
       * @return The ifsc.
       */
      public java.lang.String getIfsc() {
        java.lang.Object ref = ifsc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ifsc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ifsc = 5;</code>
       * @return The bytes for ifsc.
       */
      public com.google.protobuf.ByteString
          getIfscBytes() {
        java.lang.Object ref = ifsc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ifsc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ifsc = 5;</code>
       * @param value The ifsc to set.
       * @return This builder for chaining.
       */
      public Builder setIfsc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ifsc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ifsc = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIfsc() {
        
        ifsc_ = getDefaultInstance().getIfsc();
        onChanged();
        return this;
      }
      /**
       * <code>string ifsc = 5;</code>
       * @param value The bytes for ifsc to set.
       * @return This builder for chaining.
       */
      public Builder setIfscBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ifsc_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InterBank)
    }

    // @@protoc_insertion_point(class_scope:InterBank)
    private static final InterBankProto.InterBank DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InterBankProto.InterBank();
    }

    public static InterBankProto.InterBank getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InterBank>
        PARSER = new com.google.protobuf.AbstractParser<InterBank>() {
      @java.lang.Override
      public InterBank parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InterBank(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InterBank> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InterBank> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public InterBankProto.InterBank getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InterBank_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InterBank_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024InterBankProto.proto\"j\n\tInterBank\022\023\n\013s" +
      "enderAccNo\030\001 \001(\003\022\025\n\rreceiverAccNo\030\002 \001(\003\022" +
      "\016\n\006amount\030\003 \001(\001\022\023\n\013description\030\004 \001(\t\022\014\n\004" +
      "ifsc\030\005 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InterBank_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InterBank_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InterBank_descriptor,
        new java.lang.String[] { "SenderAccNo", "ReceiverAccNo", "Amount", "Description", "Ifsc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
